# Generated by Django 5.2.7 on 2025-10-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
