[project]
name = "b2b-logistics-portal"
version = "0.1.0"
description = "A multi-tenant backend system for a fictional logistics SaaS platform"
readme = "README.md"
authors = [{ name = "Andrew Anter", email = "andrew.anter@gmail.com" }]
requires-python = ">=3.13"
dependencies = []
