# Generated by Django 5.2.7 on 2025-10-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='has_been_processed',
        ),
    ]
