# Generated by Django 5.2.7 on 2025-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_has_been_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_been_processed',
            field=models.BooleanField(default=False),
        ),
    ]
