# Generated by Django 5.2.7 on 2025-10-04 09:17

import apps.companies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('domain', models.CharField(db_index=True, max_length=50, unique=True, validators=[apps.companies.validators.validate_subdomain_name])),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
