# Generated by Django 5.2.7 on 2025-10-03 09:00

import apps.companies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[apps.companies.validators.validate_subdomain_name]),
        ),
    ]
